//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cleric_H
#define METASPRITE_cleric_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cleric_TILE_ORIGIN 0
#define cleric_TILE_W 16
#define cleric_TILE_H 16
#define cleric_WIDTH 48
#define cleric_HEIGHT 48
#define cleric_TILE_COUNT 36
#define cleric_PALETTE_COUNT 1
#define cleric_COLORS_PER_PALETTE 4
#define cleric_TOTAL_COLORS 4
#define cleric_PIVOT_X 24
#define cleric_PIVOT_Y 24
#define cleric_PIVOT_W 48
#define cleric_PIVOT_H 48
extern const metasprite_t* const cleric_metasprites[1];

BANKREF_EXTERN(cleric)

extern const palette_color_t cleric_palettes[4];
extern const uint8_t cleric_tiles[576];

#endif
