//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cleric_down_H
#define METASPRITE_cleric_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cleric_down_TILE_ORIGIN 0
#define cleric_down_TILE_W 8
#define cleric_down_TILE_H 8
#define cleric_down_WIDTH 16
#define cleric_down_HEIGHT 16
#define cleric_down_TILE_COUNT 10
#define cleric_down_PALETTE_COUNT 1
#define cleric_down_COLORS_PER_PALETTE 4
#define cleric_down_TOTAL_COLORS 4
#define cleric_down_PIVOT_X 8
#define cleric_down_PIVOT_Y 8
#define cleric_down_PIVOT_W 16
#define cleric_down_PIVOT_H 16
extern const metasprite_t* const cleric_down_metasprites[3];

BANKREF_EXTERN(cleric_down)

extern const palette_color_t cleric_down_palettes[4];
extern const uint8_t cleric_down_tiles[160];

#endif
