//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cleric_up_H
#define METASPRITE_cleric_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cleric_up_TILE_ORIGIN 0
#define cleric_up_TILE_W 16
#define cleric_up_TILE_H 16
#define cleric_up_WIDTH 16
#define cleric_up_HEIGHT 16
#define cleric_up_TILE_COUNT 12
#define cleric_up_PALETTE_COUNT 1
#define cleric_up_COLORS_PER_PALETTE 4
#define cleric_up_TOTAL_COLORS 4
#define cleric_up_PIVOT_X 8
#define cleric_up_PIVOT_Y 8
#define cleric_up_PIVOT_W 16
#define cleric_up_PIVOT_H 16
extern const metasprite_t* const cleric_up_metasprites[3];

BANKREF_EXTERN(cleric_up)

extern const palette_color_t cleric_up_palettes[4];
extern const uint8_t cleric_up_tiles[192];

#endif
