//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cleric_sprite_H
#define METASPRITE_cleric_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cleric_sprite_TILE_ORIGIN 0
#define cleric_sprite_TILE_W 16
#define cleric_sprite_TILE_H 16
#define cleric_sprite_WIDTH 16
#define cleric_sprite_HEIGHT 16
#define cleric_sprite_TILE_COUNT 36
#define cleric_sprite_PALETTE_COUNT 1
#define cleric_sprite_COLORS_PER_PALETTE 4
#define cleric_sprite_TOTAL_COLORS 4
#define cleric_sprite_PIVOT_X 8
#define cleric_sprite_PIVOT_Y 8
#define cleric_sprite_PIVOT_W 16
#define cleric_sprite_PIVOT_H 16
extern const metasprite_t* const cleric_sprite_metasprites[9];

BANKREF_EXTERN(cleric_sprite)

extern const palette_color_t cleric_sprite_palettes[4];
extern const uint8_t cleric_sprite_tiles[576];

#endif
