/*

 /GIT/DUNGEONER/GB/RES/CLERIC.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___git_dungeoner_gb_res_cleric_h_INCLUDE
#define ___git_dungeoner_gb_res_cleric_h_INCLUDE

/* Bank of tiles. */
#define clericBank 0
extern const unsigned char clericTLE0[];
extern const unsigned char clericTLE1[];
extern const unsigned char clericTLE2[];
extern const unsigned char clericTLE3[];
extern const unsigned char clericTLE4[];
extern const unsigned char clericTLE5[];
extern const unsigned char clericTLE6[];
extern const unsigned char clericTLE7[];
extern const unsigned char clericTLE8[];

#endif

/* End of /GIT/DUNGEONER/GB/RES/CLERIC.H */
