//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fighter_H
#define METASPRITE_fighter_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fighter_TILE_ORIGIN 0
#define fighter_TILE_W 16
#define fighter_TILE_H 16
#define fighter_WIDTH 48
#define fighter_HEIGHT 48
#define fighter_TILE_COUNT 36
#define fighter_PALETTE_COUNT 1
#define fighter_COLORS_PER_PALETTE 4
#define fighter_TOTAL_COLORS 4
#define fighter_PIVOT_X 24
#define fighter_PIVOT_Y 24
#define fighter_PIVOT_W 48
#define fighter_PIVOT_H 48
extern const metasprite_t* const fighter_metasprites[1];

BANKREF_EXTERN(fighter)

extern const palette_color_t fighter_palettes[4];
extern const uint8_t fighter_tiles[576];

#endif
