//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fighter_sprite_H
#define METASPRITE_fighter_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fighter_sprite_TILE_ORIGIN 0
#define fighter_sprite_TILE_W 16
#define fighter_sprite_TILE_H 16
#define fighter_sprite_WIDTH 16
#define fighter_sprite_HEIGHT 16
#define fighter_sprite_TILE_COUNT 36
#define fighter_sprite_PALETTE_COUNT 1
#define fighter_sprite_COLORS_PER_PALETTE 4
#define fighter_sprite_TOTAL_COLORS 4
#define fighter_sprite_PIVOT_X 8
#define fighter_sprite_PIVOT_Y 8
#define fighter_sprite_PIVOT_W 16
#define fighter_sprite_PIVOT_H 16
extern const metasprite_t* const fighter_sprite_metasprites[9];

BANKREF_EXTERN(fighter_sprite)

extern const palette_color_t fighter_sprite_palettes[4];
extern const uint8_t fighter_sprite_tiles[576];

#endif
