/*

 /GIT/DUNGEONER/GB/RES/FIGHTER.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___git_dungeoner_gb_res_fighter_h_INCLUDE
#define ___git_dungeoner_gb_res_fighter_h_INCLUDE

#include <gb/metasprites.h>

/* Bank of tiles. */
#define fighterBank 0
extern const unsigned char fighterTLE0[];
extern const metasprite_t ms_fighterTLE0[];
extern const unsigned char fighterTLE1[];
extern const metasprite_t ms_fighterTLE1[];
extern const unsigned char fighterTLE2[];
extern const metasprite_t ms_fighterTLE2[];
extern const unsigned char fighterTLE3[];
extern const metasprite_t ms_fighterTLE3[];
extern const unsigned char fighterTLE4[];
extern const metasprite_t ms_fighterTLE4[];
extern const unsigned char fighterTLE5[];
extern const metasprite_t ms_fighterTLE5[];
extern const unsigned char fighterTLE6[];
extern const metasprite_t ms_fighterTLE6[];
extern const unsigned char fighterTLE7[];
extern const metasprite_t ms_fighterTLE7[];
extern const unsigned char fighterTLE8[];
extern const metasprite_t ms_fighterTLE8[];

#endif

/* End of /GIT/DUNGEONER/GB/RES/FIGHTER.H */
