//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fighter_up_H
#define METASPRITE_fighter_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fighter_up_TILE_ORIGIN 0
#define fighter_up_TILE_W 8
#define fighter_up_TILE_H 8
#define fighter_up_WIDTH 16
#define fighter_up_HEIGHT 16
#define fighter_up_TILE_COUNT 10
#define fighter_up_PALETTE_COUNT 1
#define fighter_up_COLORS_PER_PALETTE 4
#define fighter_up_TOTAL_COLORS 4
#define fighter_up_PIVOT_X 8
#define fighter_up_PIVOT_Y 8
#define fighter_up_PIVOT_W 16
#define fighter_up_PIVOT_H 16
extern const metasprite_t* const fighter_up_metasprites[3];

BANKREF_EXTERN(fighter_up)

extern const palette_color_t fighter_up_palettes[4];
extern const uint8_t fighter_up_tiles[160];

#endif
