//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_goblin_up_H
#define METASPRITE_goblin_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define goblin_up_TILE_ORIGIN 0
#define goblin_up_TILE_W 8
#define goblin_up_TILE_H 8
#define goblin_up_WIDTH 16
#define goblin_up_HEIGHT 16
#define goblin_up_TILE_COUNT 5
#define goblin_up_PALETTE_COUNT 1
#define goblin_up_COLORS_PER_PALETTE 4
#define goblin_up_TOTAL_COLORS 4
#define goblin_up_PIVOT_X 8
#define goblin_up_PIVOT_Y 8
#define goblin_up_PIVOT_W 16
#define goblin_up_PIVOT_H 16
extern const metasprite_t* const goblin_up_metasprites[3];

BANKREF_EXTERN(goblin_up)

extern const palette_color_t goblin_up_palettes[4];
extern const uint8_t goblin_up_tiles[80];

#endif
