//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_goblin_left_H
#define METASPRITE_goblin_left_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define goblin_left_TILE_ORIGIN 0
#define goblin_left_TILE_W 8
#define goblin_left_TILE_H 8
#define goblin_left_WIDTH 16
#define goblin_left_HEIGHT 16
#define goblin_left_TILE_COUNT 10
#define goblin_left_PALETTE_COUNT 1
#define goblin_left_COLORS_PER_PALETTE 4
#define goblin_left_TOTAL_COLORS 4
#define goblin_left_PIVOT_X 8
#define goblin_left_PIVOT_Y 8
#define goblin_left_PIVOT_W 16
#define goblin_left_PIVOT_H 16
extern const metasprite_t* const goblin_left_metasprites[3];

BANKREF_EXTERN(goblin_left)

extern const palette_color_t goblin_left_palettes[4];
extern const uint8_t goblin_left_tiles[160];

#endif
