//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_goblin_down_H
#define METASPRITE_goblin_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define goblin_down_TILE_ORIGIN 0
#define goblin_down_TILE_W 8
#define goblin_down_TILE_H 8
#define goblin_down_WIDTH 16
#define goblin_down_HEIGHT 16
#define goblin_down_TILE_COUNT 5
#define goblin_down_PALETTE_COUNT 1
#define goblin_down_COLORS_PER_PALETTE 4
#define goblin_down_TOTAL_COLORS 4
#define goblin_down_PIVOT_X 8
#define goblin_down_PIVOT_Y 8
#define goblin_down_PIVOT_W 16
#define goblin_down_PIVOT_H 16
extern const metasprite_t* const goblin_down_metasprites[3];

BANKREF_EXTERN(goblin_down)

extern const palette_color_t goblin_down_palettes[4];
extern const uint8_t goblin_down_tiles[80];

#endif
