/*

 /GIT/DUNGEONER/GB/RES/ROGUE.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___git_dungeoner_gb_res_rogue_h_INCLUDE
#define ___git_dungeoner_gb_res_rogue_h_INCLUDE

/* Bank of tiles. */
#define rogue_tilesBank 0
extern const unsigned char rogue_tilesTLE0[];
extern const unsigned char rogue_tilesTLE1[];
extern const unsigned char rogue_tilesTLE2[];
extern const unsigned char rogue_tilesTLE3[];
extern const unsigned char rogue_tilesTLE4[];
extern const unsigned char rogue_tilesTLE5[];
extern const unsigned char rogue_tilesTLE6[];
extern const unsigned char rogue_tilesTLE7[];
extern const unsigned char rogue_tilesTLE8[];

#endif

/* End of /GIT/DUNGEONER/GB/RES/ROGUE.H */
