//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_rogue_H
#define METASPRITE_rogue_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define rogue_TILE_ORIGIN 0
#define rogue_TILE_W 16
#define rogue_TILE_H 16
#define rogue_WIDTH 48
#define rogue_HEIGHT 48
#define rogue_TILE_COUNT 36
#define rogue_PALETTE_COUNT 1
#define rogue_COLORS_PER_PALETTE 4
#define rogue_TOTAL_COLORS 4
#define rogue_PIVOT_X 24
#define rogue_PIVOT_Y 24
#define rogue_PIVOT_W 48
#define rogue_PIVOT_H 48
extern const metasprite_t* const rogue_metasprites[1];

BANKREF_EXTERN(rogue)

extern const palette_color_t rogue_palettes[4];
extern const uint8_t rogue_tiles[576];

#endif
