/*

 /GIT/DUNGEONER/GB/RES/WINDOW_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___git_dungeoner_gb_res_window_tiles_h_INCLUDE
#define ___git_dungeoner_gb_res_window_tiles_h_INCLUDE

/* Bank of tiles. */
#define window_tilesBank 0
/* Start of tile array. */
extern const unsigned char window_tiles[];

#endif

/* End of /GIT/DUNGEONER/GB/RES/WINDOW_TILES.H */
