//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_wizard_H
#define METASPRITE_wizard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_TILE_ORIGIN 0
#define wizard_TILE_W 16
#define wizard_TILE_H 16
#define wizard_WIDTH 48
#define wizard_HEIGHT 48
#define wizard_TILE_COUNT 36
#define wizard_PALETTE_COUNT 1
#define wizard_COLORS_PER_PALETTE 4
#define wizard_TOTAL_COLORS 4
#define wizard_PIVOT_X 24
#define wizard_PIVOT_Y 24
#define wizard_PIVOT_W 48
#define wizard_PIVOT_H 48
extern const metasprite_t* const wizard_metasprites[1];

BANKREF_EXTERN(wizard)

extern const palette_color_t wizard_palettes[4];
extern const uint8_t wizard_tiles[576];

#endif
