//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_wizard_sprite_H
#define METASPRITE_wizard_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_sprite_TILE_ORIGIN 0
#define wizard_sprite_TILE_W 16
#define wizard_sprite_TILE_H 16
#define wizard_sprite_WIDTH 16
#define wizard_sprite_HEIGHT 16
#define wizard_sprite_TILE_COUNT 36
#define wizard_sprite_PALETTE_COUNT 1
#define wizard_sprite_COLORS_PER_PALETTE 4
#define wizard_sprite_TOTAL_COLORS 4
#define wizard_sprite_PIVOT_X 8
#define wizard_sprite_PIVOT_Y 8
#define wizard_sprite_PIVOT_W 16
#define wizard_sprite_PIVOT_H 16
extern const metasprite_t* const wizard_sprite_metasprites[9];

BANKREF_EXTERN(wizard_sprite)

extern const palette_color_t wizard_sprite_palettes[4];
extern const uint8_t wizard_sprite_tiles[576];

#endif
