//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_wizard_left_H
#define METASPRITE_wizard_left_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_left_TILE_ORIGIN 0
#define wizard_left_TILE_W 8
#define wizard_left_TILE_H 8
#define wizard_left_WIDTH 16
#define wizard_left_HEIGHT 16
#define wizard_left_TILE_COUNT 10
#define wizard_left_PALETTE_COUNT 1
#define wizard_left_COLORS_PER_PALETTE 4
#define wizard_left_TOTAL_COLORS 4
#define wizard_left_PIVOT_X 8
#define wizard_left_PIVOT_Y 8
#define wizard_left_PIVOT_W 16
#define wizard_left_PIVOT_H 16
extern const metasprite_t* const wizard_left_metasprites[3];

BANKREF_EXTERN(wizard_left)

extern const palette_color_t wizard_left_palettes[4];
extern const uint8_t wizard_left_tiles[160];

#endif
