/*

 /GIT/DUNGEONER/GB/RES/WIZARD.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___git_dungeoner_gb_res_wizard_h_INCLUDE
#define ___git_dungeoner_gb_res_wizard_h_INCLUDE

/* Bank of tiles. */
#define wizardBank 0
extern const unsigned char wizardTLE0[];
extern const unsigned char wizardTLE1[];
extern const unsigned char wizardTLE2[];
extern const unsigned char wizardTLE3[];
extern const unsigned char wizardTLE4[];
extern const unsigned char wizardTLE5[];
extern const unsigned char wizardTLE6[];
extern const unsigned char wizardTLE7[];
extern const unsigned char wizardTLE8[];

#endif

/* End of /GIT/DUNGEONER/GB/RES/WIZARD.H */
