[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.thumbv4t-none-eabi]
rustflags = [
    "-Clink-arg=-Tgba.ld",
    "-Ctarget-cpu=arm7tdmi",
    "-Cforce-frame-pointers=yes"
]
runner = ["mgba", "-C", "logToStdout=1", "-C", "logLevel.gba.debug=127", "-6"]

[target.armv4t-none-eabi]
rustflags = [
    "-Clink-arg=-Tgba.ld",
    "-Ctarget-cpu=arm7tdmi",
    "-Cforce-frame-pointers=yes"
]
runner = ["mgba", "-C", "logToStdout=1", "-C", "logLevel.gba.debug=127", "-6"]