/*

 ROOM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 21
   Tile set      : Z:\home\cass-forest\Documents\gb_tools\GBTD\dungeon_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room_h_INCLUDE
#define __room_h_INCLUDE

#define dungeon_roomWidth 21
#define dungeon_roomHeight 21
#define dungeon_roomBank 0

extern const unsigned char dungeon_room[];

#endif

/* End of ROOM.H */
